require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.3

  Exclude:
    - ./**/schema.rb
    - Gemfile
    - bin/*
    - bundle/**/*
    - vendor/**/*

  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: enable

Naming/VariableNumber:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - app/api/**/*.rb
    - lib/tasks/**/*.rake
    - config/**/*.rb

Style/BlockDelimiters:
  Exclude:
    - spec/**/*.rb

Style/SignalException:
  Exclude:
    - app/services/**/*.rb

Rails:
  Enabled: true

Rails/UnknownEnv:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/ParameterLists:
  Max: 10

Metrics/MethodLength:
  Max: 15

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    "%i": "[]"
    "%I": "[]"
    "%r": "{}"
    "%w": "()"
    "%W": "()"

Style/RegexpLiteral:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Style/ClassAndModuleChildren:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false
