version: "3"
services:
  # TODO: volumes for uploaded files
  web:
    build: .
    image: ghcr.io/zhulik/dbot:${GITHUB_SHA}
    env_file:
      - config.env
    ports:
      - "3000:3000"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./public/uploads/:/app/public/uploads

  poller:
    build: .
    image: ghcr.io/zhulik/dbot:${GITHUB_SHA}
    env_file:
      - config.env
    command: bash -c "bundle exec rake telegram:bot:delete_webhook && bundle exec rake telegram:bot:poller"

  sidekiq:
    build: .
    image: ghcr.io/zhulik/dbot:${GITHUB_SHA}
    env_file:
      - config.env
    command: bundle exec sidekiq
