version: "3"
services:
  # TODO: volumes for uploaded files
  web:
    build: .
    image: ghcr.io/zhulik/dbot:${GITHUB_SHA}
    env_file:
      - config.env
    ports:
      - "3000:3000"
    command: bundle exec puma -C config/puma.rb

  poller:
    build: .
    image: ghcr.io/zhulik/dbot:${GITHUB_SHA}
    env_file:
      - config.env
    command: bundle exec rake telegram:bot:poller
