version: "3"
services:
  web:
    build: .
    env_file:
      - config.env
    command: bundle exec puma -C config/puma.rb

  poller:
    build: .
    env_file:
      - config.env
    command: bundle exec rake telegram:bot:poller
