test:
  secret_key_base: 0e2b149184cf25805c6f6a3b25377c4ef8a3bfea137ad13773a331d04538fcfa5a923ddbdf0dae0c370f5dc4bbc39943b4c8c25107d086709280a8fba67cccac

  telegram:
    bot:
      token: test_bot_token
      username: BOT_NAME
  yandex_translator: test_translator_token
  yandex_dictionary: test_bot_token
