development:
  service: Disk
  root: <%= Rails.root.join("public/uploads") %>

test:
  service: Disk
  root: <%= Rails.root.join("public/uploads") %>

production:
  service: Disk
  root: <%= Rails.root.join("public/uploads") %>