name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libpq-dev

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
          bundler-cache: true

      - uses: harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: "13"
          postgresql db: dbot_test
          postgresql user: postgres
          postgresql password: password

      - uses: zhulik/redis-action@v1.0.0
        with:
          redis version: "5"

      - name: Prepare
        env:
          RAILS_ENV: test
          DATABASE_NAME: dbot_test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: password
          SIDEKIQ_REDIS_URL: redis://127.0.0.1:6379/1
          SESSION_REDIS_URL: redis://127.0.0.1:6379/2
          YANDEX_DICTIONARY_TOKEN: test
          YANDEX_TRANSLATOR_TOKEN: test
          VOICERSS_TOKEN: test
        run: |
          mv config.ci.env config.env
          bundle exec rake db:create db:schema:load

      - name: Check with rubocop
        run: bundle exec rubocop

      - name: Test with rspec
        env:
          DATABASE_NAME: dbot_test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: password
          SIDEKIQ_REDIS_URL: redis://127.0.0.1:6379/1
          SESSION_REDIS_URL: redis://127.0.0.1:6379/2
          YANDEX_DICTIONARY_TOKEN: test
          YANDEX_TRANSLATOR_TOKEN: test
          VOICERSS_TOKEN: test
        run: bundle exec rspec

      - name: Build containers
        run: |
          # TODO: cache
          docker-compose build

      - name: Publish branch containers
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

          docker-compose push

      - name: Publish latest containers
        # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          GITHUB_SHA=latest docker-compose push
